resourceGroup = "myAssignment"
managedIdentityAcr = "containerappmidentity"
location = "westeurope"
myContainerRegistry= "exodusacr"
myContainerAppEnv= "mycontainerappenv"
myLogAnalytics= "myloganalyticsname"
